#!/bin/sh

if [ $# = 1 ]
then
    extn=txt
else
    if [ $# = 2 ]
    then
        extn=$2
    else
        echo "usage: rfc <rfc number> [format (ps|txt)]" 2>&1
        exit 1
    fi
fi

dname=${RFCDIR:-$HOME/doc/standards/rfcs}
mkdir -p $dname
fname=$dname/rfc$1.$extn

if [ \! -f $fname ] 
then
    code=`curl -s -w %{http_code} -o $fname http://www.ietf.org/rfc/rfc$1.$extn`
    if [ `expr $code / 100` -ne 2 ]
    then
      rm $fname
      echo "fetch failed: $code" 1>&2
      exit 1
    fi
    chmod a-w $fname
fi
echo $fname
